export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const RESET_PASSWORD_MAIL_FAIL = 'RESET_PASSWORD_MAIL_FAIL';
export const RESET_PASSWORD_SET_PASSWORD_FAIL = 'RESET_PASSWORD_MAIL_FAIL';
export const CHANGE_PASSWORD_FAIL = 'RESET_PASSWORD_MAIL_FAIL';


export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const CREATE_CAL_SUCCESS = 'CREATE_CAL_SUCCESS';
export const CREATE_CAL_FAIL = 'CREATE_CAL_FAIL';
export const CAL_LOADING = 'CAL_LOADING';
export const CAL_LOADING_STOP = 'CAL_LOADING_STOP';


export const GET_SELF_CAL_SUCCESS = 'GET_SELF_CAL_SUCCESS';
export const GET_SELF_CAL_FAIL = 'GET_SELF_CAL_FAIL';

export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAIL = 'CREATE_EVENT_FAIL';

export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAIL = 'UPDATE_EVENT_FAIL';

export const GET_OTHERS_CAL_SUCCESS = 'GET_OTHERS_CAL_SUCCESS';
export const GET_OTHERS_CAL_FAIL = 'GET_OTHERS_CAL_FAIL';

export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';
export const DELETE_EVENT_FAIL = 'DELETE_EVENT_FAIL';

export const CLEAR_EVENT_PROFILE = 'CLEAR_EVENT_PROFILE';

export const GET_RECEIVED_INVITATIONS_SUCCESS = 'GET_RECEIVED_INVITATIONS_SUCCESS';
export const GET_RECEIVED_INVITATIONS_FAIL = 'GET_RECEIVED_INVITATIONS_FAIL';

export const GET_SENT_INVITATIONS_SUCCESS = 'GET_SENT_INVITATIONS_SUCCESS';
export const GET_SENT_INVITATIONS_FAIL = 'GET_SENT_INVITATIONS_FAIL';

export const ACCEPT_INVITATION_SUCCESS = 'ACCEPT_INVITATION_SUCCESS';
export const ACCEPT_INVITATION_FAIL = 'ACCEPT_INVITATION_FAIL';

export const REJECT_INVITATION_SUCCESS = 'REJECT_INVITATION_SUCCESS';
export const REJECT_INVITATION_FAIL = 'REJECT_INVITATION_FAIL';

export const SUGGEST_INVITATION_SUCCESS = 'SUGGEST_INVITATION_SUCCESS';
export const SUGGEST_INVITATION_FAIL = 'SUGGEST_INVITATION_FAIL';

export const SEND_INVITATION_SUCCESS = 'SEND_INVITATION_SUCCESS';
export const SEND_INVITATION_FAIL = 'SEND_INVITATION_FAIL';

export const ADD_INVITATION_TO_EVENT = 'ADD_INVITATION_TO_EVENT';

export const DELETE_INVITATION_SUCCESS = 'DELETE_INVITATION_SUCCESS';
export const DELETE_INVITATION_FAIL = 'DELETE_INVITATION_FAIL';

export const SET_SLOTS_SUCCESS = 'SET_SLOTS_SUCCESS';
export const SET_SLOTS_FAIL = 'SET_SLOTS_FAIL';

export const GET_SLOTS_SUCCESS = 'GET_SLOTS_SUCCESS';
export const GET_SLOTS_FAIL = 'GET_SLOTS_FAIL';

export const GET_DOCTORS_SUCCESS = 'GET_DOCTORS_SUCCESS';
export const GET_DOCTORS_FAIL = 'GET_DOCTORS_FAIL';

export const GET_DOCTOR_FEEDBACK_SUCCESS = 'GET_DOCTOR_FEEDBACK_SUCCESS';
export const GET_DOCTOR_FEEDBACK_FAIL = 'GET_DOCTOR_FEEDBACK_FAIL';

export const GET_PATIENTS_SUCCESS = 'GET_PATIENTS_SUCCESS';
export const GET_PATIENTS_FAIL = 'GET_PATIENTS_FAIL';

export const GET_MY_DOCTORS_SUCCESS = 'GET_MY_DOCTORS_SUCCESS';
export const GET_MY_DOCTORS_FAIL = 'GET_MY_DOCTORS_FAIL';

export const SUBMIT_FEEDBACK_SUCCESS = 'SUBMIT_FEEDBACK_SUCCESS';
export const SUBMIT_FEEDBACK_FAIL = 'SUBMIT_FEEDBACK_FAIL';

export const SAVE_PRESCRIPTION_SUCCESS = 'SAVE_PRESCRIPTION_SUCCESS';
export const SAVE_PRESCRIPTION_FAIL = 'SAVE_PRESCRIPTION_FAIL';

export const GET_PRESCRIPTIONS_SUCCESS = 'GET_PRESCRIPTIONS_SUCCESS';
export const GET_PRESCRIPTIONS_FAIL = 'GET_PRESCRIPTIONS_FAIL';
